[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_movie = "2to1m9qHAKQ8WdcKdKAhZJm6UkFACPgLqso3FPsuHe3M"

[programs.devnet]
solana_movie = "2to1m9qHAKQ8WdcKdKAhZJm6UkFACPgLqso3FPsuHe3M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
