import { Provider } from "@/components/ui/provider";
import { WalletProvider } from "@/providers";
import QueryProvider from "@/providers/QueryProvider";
import { SolanaProvider } from "@/providers/SolanaProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <QueryProvider>
            <WalletProvider>
              <SolanaProvider>{children}</SolanaProvider>
            </WalletProvider>
          </QueryProvider>
        </Provider>
      </body>
    </html>
  );
}
