"use client";

import { Grid, Skeleton } from "@chakra-ui/react";

export default function SkeletonMovieGrid() {
  return (
    <Grid templateColumns="repeat(6, 1fr)" gap="6" w="100%">
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
      <Skeleton
        display="flex"
        flexDirection="column"
        gap="2"
        borderRadius="xl"
        h="296px"
        flex="1"
        width="100%"
      ></Skeleton>
    </Grid>
  );
}
